---
title: "Practical4 Homework"
author: "xu"
date: "2023-10-27"
output: html_document
---

load the packages
```{r setup, include=FALSE}

library(tidyverse)
library(janitor)
library(sf)
library(countrycode)
library(tmaptools)
library(tmap)
library(RSQLite)

```

Load the csv and shape files
```{r}
#load the csv file and assign na to all null values
#the data set has been renamed as 'homework_dataset' and it's under the directory 'datafolder' 
dataset <- read_csv("datafolder/homework_dataset.csv",na=" ") %>%
   dplyr::rename(index_2010="gii_2010",index_2019="gii_2019")%>%
  select(country,index_2010,index_2019,iso3)%>%
mutate(iso_code=countrycode(country, origin = 'country.name', destination = 'iso2c'))%>%
  mutate(iso_code2=countrycode(iso3, origin ='iso3c', destination = 'iso2c'))

shapefile <- st_read("World_Countries_Generalized/World_Countries_Generalized.shp")

```



```{r}
dataset <- na.omit(dataset)
#remove the NAs in dataset
newdataset <- dataset %>%
  mutate(difference=(index_2019-index_2010))
# create a new column using the index of 2010 subtract from the index of 2019


joined_data <- shapefile %>% 
 
  left_join(., 
            newdataset,
            by = c("ISO" = "iso_code"))
# left join the data
```


```{r}
tmap_mode("plot")
qtm(joined_data, 
    fill = "difference")
``

```



```{r}
breaks=c(0.0,0.2,0.4,0.6,0.8,1.0)
diffbreaks=c(-0.4,-0.3,-0.2,-0.1,0,0.1)
# preserve size not direction like WGS84
joinshp = st_transform(joined_data, crs = "+proj=moll")
# plot each map

tm1 <- tm_shape(joinshp) + 
  tm_polygons("index_2019", 
              breaks=breaks,
              palette="PuBu")+
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(a)", position=c(0,0.85), size=1.5)

tm2 <- tm_shape(joinshp) + 
  tm_polygons("index_2010",
              breaks=breaks,
              palette="PuBu") + 
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(b)", position=c(0,0.85), size=1.5)

tm3 <- tm_shape(joinshp) + 
  tm_polygons("difference",
              #style="fixed",
              breaks=diffbreaks,
              palette=("Blues"),
               midpoint = NA)+ 
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(c)", position=c(0,0.85), size=1.5)


legend <- tm_shape(joinshp) + 
  tm_polygons("index_2019", 
              breaks=breaks,
              palette="PuBu",
              title = "GII")+
  tm_legend(show=TRUE)+
  #asp is aspect ratio! 
  tm_layout(legend.only = TRUE, legend.position=c(0.3,0.25),asp=0.1)+
  tm_shape(joinshp) +
  tm_polygons("difference",
                 palette=("Blues"),
               midpoint = NA,
               title="HDI difference \n(2019-2010)") +
    #tm_scale_bar(position=c(0.2,0.04), text.size=0.6)+
    tm_compass(north=0, position=c(0.6,0.6))+
    tm_layout(legend.only = TRUE, legend.position=c(0.1,0.1),asp=0.1)+
    tm_credits("Mapped data:\nUN Human Development Index\nWorld outline:\nArcGIS Hub 
               ", position=c(0.35,0.2), just="left")

# in tmap can't make legends side by side unless use this workaround: 
#https://github.com/r-tmap/tmap/issues/476 

t=tmap_arrange(tm1, tm2, tm3, legend, ncol=2)


t
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
